name: "Esox"

on:
  push:

jobs:
  gofmt:
    name: "go fmt"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683" # v4
      - uses: "actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b" # v5
        with:
          go-version-file: "./go.mod"

      - run: "test -z $(gofmt -l .)"

  govet:
    name: "go vet"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683" # v4
      - uses: "actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b" # v5
        with:
          go-version-file: "./go.mod"

      - run: "go vet ./..."

  gotest:
    name: "go test"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683" # v4
      - uses: "actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b" # v5
        with:
          go-version-file: "./go.mod"

      - run: "go test ./..."
